// AIKEY-l4qkxonqry2b4gj7bsrkqpryiy
//! Typed detection results produced by the AI-key check pipeline.

use std::fmt;

// ── Detection (top-level) ──────────────────────────────────────────────────

/// All the ways a file or submission can be flagged.
///
/// Detections are collected by `check-ai-key` from two independent sources:
///
/// * The **AI-content scan** (`AiEnv` implementations in this crate):
///   triggered only on files that lack the submission key.
/// * The **RASP scan** ([`RaspScanner`][crate::rasp::RaspScanner]):
///   triggered on *all* changed files regardless of key presence, because a
///   malicious agent could trivially include the key to bypass the AI scan.
#[derive(Debug, Clone)]
pub enum Detection {
    /// A changed file is missing the current AI submission key.
    ///
    /// This is **informational** on its own; it only becomes a CI failure
    /// when paired with an [`AiContent`][Detection::AiContent] detection.
    MissingKey { path: String },

    /// A file is missing the key AND the AI scanner believes it was
    /// generated by an AI — a submission-integrity violation.
    AiContent { path: String, confidence: f64 },

    /// The RASP scanner detected a runtime exploitation pattern in this file.
    RaspAlert(RaspAlert),
}

impl Detection {
    /// Returns `true` if this detection should cause a CI failure.
    ///
    /// `MissingKey` alone is informational (human code without the key is
    /// allowed); only `AiContent` and `RaspAlert` (any severity) fail.
    pub fn is_failure(&self) -> bool {
        match self {
            Detection::MissingKey { .. } => false,
            Detection::AiContent { .. } => true,
            Detection::RaspAlert(_) => true,
        }
    }

    /// The repo-relative path associated with this detection.
    pub fn path(&self) -> &str {
        match self {
            Detection::MissingKey { path }
            | Detection::AiContent { path, .. } => path,
            Detection::RaspAlert(a) => &a.path,
        }
    }
}

// ── RaspAlert ─────────────────────────────────────────────────────────────

/// A single RASP detection event.
#[derive(Debug, Clone)]
pub struct RaspAlert {
    pub kind:     RaspAlertKind,
    pub path:     String,
    /// Human-readable explanation of what was found.
    pub detail:   String,
    pub severity: Severity,
}

// ── RaspAlertKind ──────────────────────────────────────────────────────────

/// Categorises the exploitation technique a RASP alert was triggered by.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RaspAlertKind {
    /// Shell metacharacters (`$(…)`, `` `…` ``, `${IFS}`, pipe-to-shell) in a
    /// file path or name — the primary vector used by the `hackerbot-claw`
    /// campaign (branch-name and filename shell injection).
    ShellInjectionInPath,

    /// Dangerous patterns added to `.github/workflows/` files: `curl|sh`-style
    /// droppers, or unquoted `${{ github.event.… }}` in `run:` steps
    /// (expression-injection, cf. CVE-2025-30066 class of attacks).
    CiWorkflowTampering,

    /// Prompt-injection phrases or social-engineering directives found in
    /// `CLAUDE.md`, `AGENTS.md`, or any `*.agents_.md` file — targeting AI
    /// agents that read those files as trusted instruction context.
    AgentContextPoisoning,

    /// An auto-executing function (`func init()` in Go, `#[ctor]` in Rust)
    /// that contains network or process-exec calls — the backdoor technique
    /// documented in the `hackerbot-claw` Go `init()` campaign.
    AutoexecBackdoor,

    /// A large base64-encoded payload co-located with a shell execution
    /// context (`eval`, `base64 -d`, `run:` block), or encoded in the file
    /// path itself.
    Base64Payload,
}

impl fmt::Display for RaspAlertKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ShellInjectionInPath  => write!(f, "shell-injection-in-path"),
            Self::CiWorkflowTampering  => write!(f, "ci-workflow-tampering"),
            Self::AgentContextPoisoning => write!(f, "agent-context-poisoning"),
            Self::AutoexecBackdoor      => write!(f, "autoexec-backdoor"),
            Self::Base64Payload         => write!(f, "base64-payload"),
        }
    }
}

// ── Severity ───────────────────────────────────────────────────────────────

/// Severity levels for RASP alerts, ordered from least to most serious.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Severity {
    /// Suspicious but plausible in benign code; informational.
    Low,
    /// Uncommon in legitimate code; warrants review.
    Medium,
    /// Strong exploitation signal; should fail CI.
    High,
    /// Definitive exploitation pattern; halt and report.
    Critical,
}

impl fmt::Display for Severity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Low      => write!(f, "LOW"),
            Self::Medium   => write!(f, "MEDIUM"),
            Self::High     => write!(f, "HIGH"),
            Self::Critical => write!(f, "CRITICAL"),
        }
    }
}
